### PR TITLE
Week0

### PR DESCRIPTION
**Pull request by raghucodlab**

### CODE REVIEW

**Comment by alfadelta10010** [comment]
I'm not accepting your assignment. Clearly, you did not configure your Git correctly.

**Review by alfadelta10010 — CHANGES_REQUESTED** [review]
Please redo. Your file is unreadable.

**Comment by raghucodlab** [comment]
Am I supposed to just upload the file again in github?

**Comment by alfadelta10010** [comment]
Meet me in college tomorrow

**Comment by raghucodlab** [comment]
Ok bro where should I come to meet you Tomorrow bro and at what time?

**Pull request closed without merging**
